version: '3.4'

services:
  sqldb:
    image: mcr.microsoft.com/mssql/server
    container_name: sourcingsqldb
    restart: always
    ports:
      - "1433:1433"
    environment:
        
        ACCEPT_EULA: "Y"