version: '3'

services:
  consul:
    image: consul:latest
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600"
    command: "agent -dev -client=0.0.0.0 -bind=0.0.0.0"
    volumes:
      - ./consul/data:/consul/data
      - ./consul/config:/consul/config

  consul-ui:
    image: consul:latest
    container_name: consul-ui
    ports:
      - "8080:80"
    command: "agent -dev -ui -client=0.0.0.0 -bind=0.0.0.0"
    depends_on:
      - consul